version: '3'

services:
  redis:
    image: redis
    ports:
      - '6380:6379'

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=12345678
      - PGDATA=var/lib/postgres/data/pgdata
    volumes:
      - pgdata:/var/lib/postgres/data/pgdata
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  habits:
    build: .
    tty: true
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - habits

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO -S django
    depends_on:
      - redis
      - habits

volumes:
  pgdata: