# Generated by Django 5.0 on 2023-12-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('место', models.CharField(blank=True,
                                           max_length=100,
                                           null=True)),
                ('Время делать это', models.DateTimeField(auto_now=True)),
                ('Действие', models.CharField(max_length=150)),
                ('это приятная привычка?', models.BooleanField(default=False)),
                ('периодичность выполнения', models.IntegerField(
                    choices=[(1, 'every day'),
                             (2, 'every 2 day'),
                             (3, 'every 3 day'),
                             (4, 'every 4 day'),
                             (5, 'every 5 day'),
                             (6, 'every 6 day'),
                             (7, 'every 7 day')],
                    default=1)),
                ('вознаграждение', models.CharField(blank=True,
                                                    max_length=100,
                                                    null=True)),
                ('время выполнения', models.DateTimeField(default=30)),
                ('Опубликованная?', models.BooleanField(
                    choices=[
                        ('published', 'Опубликованная'),
                        ('unpublished', 'Неопубликованная')],
                    default='Неопубликованная')),
                ('Связанная привычка', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='habits.habit')),
                ('создатель привычки', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
