# Generated by Django 5.0 on 2023-12-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка',
                     'verbose_name_plural': 'привычки'},
        ),
    ]
