# Generated by Django 5.0 on 2024-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_время_делать_это_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='related_habits',
            new_name='related_habit',
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_do_it',
            field=models.TimeField(auto_now=True, verbose_name='Время делать это'),
        ),
    ]
