# Generated by Django 5.0 on 2024-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_rename_related_habits_habit_related_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_do_it',
            field=models.TimeField(verbose_name='время делать это'),
        ),
    ]
