# Generated by Django 5.0 on 2024-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_time_do_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_execution',
            field=models.TimeField(blank=True, null=True, verbose_name='последнее выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_do_it',
            field=models.TimeField(blank=True, null=True, verbose_name='время делать это'),
        ),
    ]
