# Generated by Django 5.0 on 2024-01-12 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habit_last_execution_alter_habit_time_do_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='last_execution',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time_do_it',
        ),
        migrations.AddField(
            model_name='habit',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 12), verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(17, 1, 39, 883107), verbose_name='время делать это'),
        ),
    ]
