# Generated by Django 5.0 on 2024-01-15 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits',
         '0008_remove_habit_last_execution_remove_habit_time_do_it_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_do_it',
            field=models.DateTimeField(default=datetime.datetime(
                2024, 1, 15, 12, 57, 58, 91358),
                verbose_name='время делать это'),
        ),
    ]
