# Generated by Django 4.2 on 2024-01-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_remove_habit_date_remove_habit_time_habit_time_do_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_do_it',
            field=models.DateTimeField(auto_now=True, verbose_name='время делать это'),
        ),
    ]
